GET http://localhost:3000/users

###

POST http://localhost:3000/user
Content-Type: application/json

{
    "name":"Pera",
    "password":"sifra"
}
###

POST http://localhost:3000/token
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiUGVyYSIsImlhdCI6MTY4ODkyNzg5OH0.0RKxUTmZrgtBvL9cGSUlWgRBqYpXILqNRBULMMqwOas"
}
###

POST http://localhost:3000/login
Content-Type: application/json

{
    "name":"Pera",
    "password":"sifra"
}
###
GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiUGVyYSIsImlhdCI6MTY4ODkyNzk2NCwiZXhwIjoxNjg4OTI4MDI0fQ.sBLaENixvzrbAFVTpLvuIpThA5H2ZE6yDR4VT_TBxn0
